spring:
  application:
    name: lms-lead-service
  config:
    #    no profile is selected, so use local host.
    import: "optional:configserver:http://localhost:9000"
    fail-fast: true
    retry:
      initial-interval: 1000
      max-interval: 5000
      max-attempts: 20


---
# 2. Docker profile config
spring:
  config:
    activate:
      on-profile: docker
    import: "configserver:http://config-server:9000"

---
# 3. Prod.
spring:
  config:
    activate:
      on-profile: aws-prod
    import: "optional:configserver:http://config-server:9000"